sudo: required
dist: trusty
addons:
   chrome:stable
language: node_js
node_js: 
   - "8"
before_script:
   - npm install -g --silent @angular/cli
   - "sudo chown root /opt/google/chrome/chrome-sandbox"
   - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"
script:
   - ng build --prod